[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y curl"
]

[phases.install]
cmds = [
    "npm install"
]

[phases.build]
cmds = [
    "echo 'Build complete'"
]

[start]
cmd = "npm start"