[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"
[http]
port = 3001

[[services.ports]]
port = 3001
protocol = "http"